use_frameworks!

platform :ios, '8.0'

target 'A_category_Example' do
  pod 'A_category', :path => '../'

  target 'A_category_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
